logconfig:
  version: 1
  formatters:
    precise: 
      format: '%(asctime)s - %(name)s:%(levelname)s:%(message)s'
      datefmt: "%m-%d-%Y %I:%M:%S %p %Z"
  handlers: 
    console: 
      class: logging.StreamHandler
      formatter: precise
  root:
    level: ${DJ_LOGLEVEL}
    handlers:
      - console
  loggers:
    unnamed: 
      level: ${DJ_LOGLEVEL}
      propagate: 0
      handlers: 
        - console
  disable_existing_loggers: 0