logconfig:
  version: 1
  formatters:
    precise: 
      format: '%(asctime)s - %(name)s:%(levelname)s:%(message)s'
      datefmt: "%m-%d-%Y %I:%M:%S %p %Z"
  handlers: 
    console: 
      class: logging.StreamHandler
      formatter: precise
    file: 
      class: logging.handlers.RotatingFileHandler
      formatter: precise
      filename: ${DJ_LOG_BASE_DIR}/+filename&
      maxBytes: 1024
      backupCount: 5
      encoding: utf-8
  root:
    level: ${DJ_LOGLEVEL}
    handlers:
      - console
  loggers:
    unnamed:
      level: ${DJ_LOGLEVEL}
      propagate: 0
      handlers: 
        - console
        - file
  disable_existing_loggers: 0